#:schema node_modules/wrangler/config-schema.json
name = "markdownworker"
main = "src/index.js"
compatibility_date = "2023-03-14"
compatibility_flags = ["nodejs_compat"]

browser = { binding = "MYBROWSER" }

# Binding to a Durable Object
[[durable_objects.bindings]]
name = "BROWSER"
class_name = "Browser"

[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["Browser"]